Repository together-saving/together-saving-FE, pull requests merged in 2022-02, with the labels that each got.

#36 [이동수] MoreShow Template Completed
  src/views/MoreShow/MoreShowTemplate.jsx
Labels: feature develop

#37 [김보미] Code Refactoring & Fixed Bugs
  package.json
  public/modules/challenge.json
  public/modules/challenge_account.json
  public/modules/history_acient.json
  public/modules/participatingChallenge.json
  public/modules/saving.json
  src/App.jsx
  src/components/Button.jsx
  src/pages/saving/Saving.jsx
  src/pages/saving/SavingDeposit.jsx
  src/pages/saving/SavingRoomInfoContainer.jsx
  src/pages/saving/SavingStatusContainer.jsx
  src/redux/actions/types.js
  src/redux/reducers/rootReducer.js
  src/redux/reducers/savingRequestReducer.js
  src/utils/regex.js
  src/views/deposit/DepositKeypad.jsx
  src/views/deposit/DepositView.jsx
  src/views/main/MainTabs.jsx
  src/views/saving/SavingFilterPopUp.jsx
  src/views/saving/SavingHistory.jsx
  src/views/saving/SavingHistoryItem.jsx
  src/views/saving/SavingHistoryList.jsx
  src/views/saving/SavingRate.jsx
  src/views/saving/SavingRoomInfo.jsx
  src/views/saving/SavingStartButton.jsx
  src/views/saving/SavingStatusInfo.jsx
  src/views/saving/SavingTabMenu.jsx
  yarn.lock
Labels: complete, refactoring

#41 [김보미] Implement Infinite Scroll & Add dotenv
  .gitignore
  package-lock.json
  package.json
  public/modules/autoSaving.json
  public/modules/participatingChallenge.json
  src/App.jsx
  src/components/BottomNav.jsx
  src/pages/MoreShow/MoreShow.jsx
  src/pages/main/Main.jsx
  src/utils/callApi.js
  src/utils/regex.js
  src/views/MoreShow/MoreShowTemplate.jsx
  src/views/deposit/DepositKeypad.jsx
  src/views/main/MainTabs.jsx
  src/views/more/MoreShowItem.jsx
  src/views/more/MoreShowList.jsx
  src/views/saving/AutoSavingButton.jsx
  webpack.config.js
  yarn.lock
Labels: complete, feature develop

#39 [이동수] Feature : MainPage Event banner swipe feature completion
  package-lock.json
  package.json
  src/App.jsx
  src/components/Event.jsx
  src/images/EventImage.png
  src/images/Send.png
  src/pages/challenge/ChallengeContainer.jsx
  src/pages/challenge/ChallengePaymentContainer.jsx
  src/pages/main/Main.jsx
  src/pages/saving/SavingCommunicationContainer.jsx
  src/pages/saving/SavingLankingContainer.jsx
  src/redux/reducers/challengeSummaryReducer.js
  src/views/challenge/PayBtn.jsx
  src/views/saving/SavingCommunication.jsx
  src/views/saving/SavingLanking.jsx
  src/views/saving/SavingTabMenu.jsx
  webpack.config.js
  yarn.lock
Labels: complete, feature develop

#42 [김보미] Implement Show More Info
  public/modules/challenge.json
  public/modules/challenge_account.json
  public/modules/saving.json
  public/modules/similarity.json
  src/components/ChallengeTag.jsx
  src/components/ChallengeTemplate1.jsx
  src/components/ChallengeTemplate2.jsx
  src/pages/challenge/ChallengeContainer.jsx
  src/redux/reducers/challengeSummaryReducer.js
  src/utils/callApi.js
  src/utils/regex.js
  src/views/challenge/ChallengeDescription.jsx
  src/views/challenge/ChallengeReview.jsx
  src/views/challenge/PayBtn.jsx
  src/views/deposit/DepositView.jsx
  src/views/main/ChallengeCreateAndEct.jsx
  src/views/more/MoreShowItem.jsx
  src/views/more/MoreShowList.jsx
  src/views/saving/SavingHistory.jsx
  src/views/saving/SavingHistoryItem.jsx
  src/views/saving/SavingStatusInfo.jsx
Labels: complete, feature develop

#43 [김보미] Add back-end API address
  src/App.jsx
  src/pages/challenge/ChallengeContainer.jsx
  src/pages/challenge/ChallengePaymentContainer.jsx
  src/pages/challenge/ChallengePaymentSuccess.jsx
  src/pages/saving/Saving.jsx
  src/pages/saving/SavingHistoryContainer.jsx
  src/pages/saving/SavingRoomInfoContainer.jsx
  src/pages/saving/SavingStatusContainer.jsx
  src/redux/reducers/challengeSummaryReducer.js
  src/redux/reducers/savingHistoryReducer.js
  src/redux/reducers/savingInfoReducer.js
  src/views/challenge/ChallengeDescription.jsx
  src/views/challenge/PayBtn.jsx
  src/views/deposit/SavingSuccess.jsx
  src/views/main/MainTabs.jsx
  src/views/saving/SavingRoomInfo.jsx
  src/views/saving/SavingTabMenu.jsx
  webpack.config.js
Labels: complete, feature develop

#44 [이동수] Feature : Mockdata deleted & server data connection
  package.json
  src/pages/challenge/ChallengeContainer.jsx
  src/pages/saving/Saving.jsx
  src/views/main/MainTabs.jsx
Labels: complete, refactoring

#47 [김보미] Complete connect api address
  src/App.jsx
  src/pages/saving/SavingDeposit.jsx
  src/pages/saving/SavingHistoryContainer.jsx
  src/pages/saving/SavingStatusContainer.jsx
  src/redux/reducers/challengeSummaryReducer.js
  src/redux/reducers/savingHistoryReducer.js
  src/redux/reducers/savingInfoReducer.js
  src/redux/reducers/savingRequestReducer.js
  src/views/deposit/DepositKeypad.jsx
  src/views/deposit/DepositView.jsx
  src/views/deposit/SavingSuccess.jsx
  src/views/saving/AutoSavingButton.jsx
  src/views/saving/SavingFilterPopUp.jsx
  src/views/saving/SavingHistory.jsx
  src/views/saving/SavingHistoryList.jsx
  src/views/saving/SavingRate.jsx
  src/views/saving/SavingStartButton.jsx
  src/views/saving/SavingStatusInfo.jsx
Labels: complete, feature develop

#48 [이동수] Feature : Review Modal & Like button featuring...
  src/components/ChallengeSummary.jsx
  src/components/ChallengeTemplate2.jsx
  src/components/LikeButton.jsx
  src/pages/challenge/ChallengeContainer.jsx
  src/redux/reducers/challengeSummaryReducer.js
  src/views/challenge/ChallengeReview.jsx
  src/views/challenge/Tags.jsx
  src/views/main/MainTabs.jsx
Labels: complete, feature develop, refactoring

#50 [이동수] Feature : Review Modal complete & Header Time component complete
  src/components/Event.jsx
  src/components/Thimbnail.jsx
  src/components/Time.jsx
  src/images/PhoneState.png
  src/pages/challenge/ChallengePaymentSuccess.jsx
  src/pages/main/Main.jsx
  src/redux/reducers/challengeSummaryReducer.js
  src/views/challenge/ChallengeReview.jsx
Labels: complete, feature develop

#56 [김보미] Header redesign & implement previous page
  src/components/CardList.jsx
  src/components/Event.jsx
  src/components/Header.jsx
  src/components/Thimbnail.jsx
  src/components/Time.jsx
  src/images/left_arrow.png
  src/pages/MoreShow/MoreShow.jsx
  src/pages/challenge/ChallengeContainer.jsx
  src/pages/challenge/ChallengePaymentSuccess.jsx
  src/pages/main/Main.jsx
  src/pages/saving/Saving.jsx
  src/pages/saving/SavingDeposit.jsx
  src/styles/GlobalStyle.jsx
  src/views/deposit/SavingSuccess.jsx
  src/views/main/MainTabs.jsx
  src/views/more/MoreShowList.jsx
Labels: complete, ui develop, feature develop, refactoring

#63 [이동수] Feature : Various debugging ...
  src/components/Event.jsx
  src/components/Time.jsx
  src/images/EventImage.png
  src/pages/challenge/ChallengeContainer.jsx
  src/views/challenge/ChallengeReview.jsx
  src/views/challenge/PayBtn.jsx
Labels: bug, complete, feature develop

#64 [김보미] Multiple feature fixes and refactorings
  src/components/ChallengeTemplate1.jsx
  src/components/ChallengeTemplate2.jsx
  src/components/Header.jsx
  src/components/Thumbnail.jsx
  src/components/Time.jsx
  src/pages/challenge/ChallengeContainer.jsx
  src/pages/challenge/ChallengePaymentContainer.jsx
  src/pages/main/Main.jsx
  src/pages/saving/Saving.jsx
  src/pages/saving/SavingDeposit.jsx
  src/pages/saving/SavingHistoryContainer.jsx
  src/views/challenge/ChallengeDescription.jsx
  src/views/challenge/ChallengeReview.jsx
  src/views/challenge/PayBtn.jsx
  src/views/more/MoreShowList.jsx
  src/views/saving/SavingCount.jsx
  src/views/saving/SavingHistory.jsx
  src/views/saving/SavingRate.jsx
  src/views/saving/SavingRoomInfo.jsx
  src/views/saving/SavingStartButton.jsx
  src/views/saving/SavingStatusInfo.jsx
Labels: error handling, complete, ui develop, feature develop, refactoring

#65 [김보미] Fixed Participate bug
  src/pages/challenge/ChallengeContainer.jsx
Labels: bug, complete

#68 [김보미] Add skeleton ui & fix design bug
  src/components/Header.jsx
  src/components/Thumbnail.jsx
  src/components/Time.jsx
  src/components/skeleton/ChallengeSkeleton.jsx
  src/components/skeleton/SavingHistorySkeleton.jsx
  src/components/skeleton/SavingRoomInfoSkeleton.jsx
  src/components/skeleton/SavingStatusSkeleton.jsx
  src/pages/challenge/ChallengeContainer.jsx
  src/pages/challenge/ChallengePaymentContainer.jsx
  src/pages/challenge/ChallengePaymentSuccess.jsx
  src/pages/saving/SavingHistoryContainer.jsx
  src/pages/saving/SavingRoomInfoContainer.jsx
  src/pages/saving/SavingStatusContainer.jsx
  src/views/main/MainTabs.jsx
  src/views/more/MoreShowList.jsx
  src/views/saving/SavingHistoryList.jsx
Labels: bug, complete, ui develop

#70 [김보미] Solved 404 image not found & design refactoring
  src/components/ChallengeTemplate1.jsx
  src/components/ChallengeTemplate2.jsx
  src/components/GrayBackground.jsx
  src/components/Thumbnail.jsx
  src/pages/challenge/ChallengeContainer.jsx
  src/views/challenge/ChallengeDescription.jsx
  src/views/challenge/ChallengeReview.jsx
  src/views/more/MoreShowItem.jsx
  src/views/saving/SavingRoomInfo.jsx
  src/views/saving/SavingStatusInfo.jsx
Labels: bug, complete, refactoring

#71 [이동수] Feature : communication, Lanking component complete
  src/pages/saving/SavingCommunicationContainer.jsx
  src/pages/saving/SavingLankingContainer.jsx
  src/views/saving/SavingCommunication.jsx
  src/views/saving/SavingLanking.jsx
Labels: bug, complete, feature develop

#72 [김보미] Fixed request API re-rendering page & add mode detail page
  src/components/Thumbnail.jsx
  src/hooks/useChallengeApi.jsx
  src/pages/challenge/ChallengeContainer.jsx
  src/pages/saving/SavingHistoryContainer.jsx
  src/styles/GlobalStyle.jsx
  src/views/more/MoreShowList.jsx
  src/views/saving/SavingHistory.jsx
  src/views/saving/SavingHistoryList.jsx
Labels: error handling, complete, ui develop

#73 [김보미] Fixed FinishPopup & re-design challenge payment page
  src/App.jsx
  src/components/Thumbnail.jsx
  src/images/default_profile.png
  src/pages/challenge/ChallengePaymentContainer.jsx
  src/pages/more/MoreShow.jsx
  src/styles/GlobalStyle.jsx
  src/views/challenge/ChallengeDescription.jsx
  src/views/challenge/ChallengeReview.jsx
  src/views/challenge/PayBtn.jsx
  src/views/saving/SavingRate.jsx
  src/views/saving/SavingStartButton.jsx
  src/views/saving/SavingStatusInfo.jsx
Labels: bug, complete, ui develop

#74 [이동수] Feature : SavingCommunication component complete!!
  src/styles/GlobalStyle.jsx
  src/views/challenge/ChallengeReview.jsx
  src/views/saving/SavingCommunication.jsx
Labels: bug, complete

#76 [이동수] Deploy Test Complete
  .babelrc
  package-lock.json
  package.json
  src/App.jsx
  src/utils/TokenApi.jsx
  src/views/challenge/SavingDay.jsx
  webpack.config.js
  yarn.lock
Labels: bug, complete

#77 [이동수] Feature : react-cookies library remove
  src/App.jsx
  src/pages/main/Main.jsx
  src/utils/TokenApi.jsx
  src/views/main/MainTabs.jsx
Labels: bug, complete

#79 [김보미] Edit style
  src/components/ChallengeTemplate2.jsx
  src/views/main/MainTabs.jsx
  src/views/saving/SavingLanking.jsx
Labels: complete, ui develop
