Repository together-saving/together-saving-FE, pull requests merged in 2022-01, with the labels that each got.

#2 [이동수] Create mainPage structure
  package-lock.json
  package.json
  src/imges/Community.png
  src/imges/Contents.png
  src/imges/Home.png
  src/imges/MyPage.png
  src/imges/SaveChallenge.png
  src/imges/bell.png
  src/imges/heart.png
  src/imges/savle.png
  src/pages/main/Main.jsx
  src/views/main/BottomNav.jsx
  src/views/main/Event.jsx
  src/views/main/Header.jsx
  src/views/main/MainTabs.jsx
  src/views/main/ParticipatingChallenge.jsx
  src/views/main/ParticularGroupChallenge.jsx
  src/views/main/PopularChallenge.jsx
  src/views/main/WholeChallenge.jsx
  yarn.lock
Labels: enhancement

#8 [이동수] ChallengeDetailPage Destructuring
  package-lock.json
  package.json
  src/components/BottomNav.jsx
  src/components/Event.jsx
  src/components/Header.jsx
  src/components/PopularChallenge.jsx
  src/images/BI_savle_blue.png
  src/images/Like.png
  src/modules/challenge.json
  src/pages/challenge/Challenge.jsx
  src/pages/main/Main.jsx
  src/views/challenge/ChallengeSummary.jsx
  src/views/challenge/ChallengeViews.jsx
  src/views/challenge/MainChallengeDetails.jsx
  src/views/challenge/Tags.jsx
  src/views/main/BottomNav.jsx
  src/views/main/Header.jsx
  src/views/main/MainTabs.jsx
  webpack.config.js
  yarn.lock
Labels: enhancement

#12 [이동수] Challenge Detail Page structuring almost over
  src/components/Button.jsx
  src/components/GrayBackground.jsx
  src/components/H3.jsx
  src/components/PopularChallenge.jsx
  src/modules/challenge.json
  src/pages/challenge/Challenge.jsx
  src/styles/GlobalStyle.jsx
  src/views/challenge/ChallengeDescription.jsx
  src/views/challenge/ChallengeReview.jsx
  src/views/challenge/ChallengeSummary.jsx
  src/views/challenge/MainChallengeDetails.jsx
  src/views/challenge/RefundAndCaution.jsx
  src/views/challenge/Tags.jsx
  src/views/main/ParticipatingChallenge.jsx
  src/views/main/ParticularGroupChallenge.jsx
  src/views/main/WholeChallenge.jsx
Labels: ui develop, feature develop

#13 [김보미] Add mock data challenge status
  .babelrc
  package-lock.json
  package.json
  public/modules/challenge.json
  public/modules/saving.json
  public/modules/user.json
  src/index.jsx
  src/pages/saving/Saving.jsx
  src/redux/actions/types.js
  src/redux/reducers/rootReducer.js
  src/redux/reducers/savingHistoryReducer.js
  src/redux/reducers/savingInfoReducer.js
  src/views/challenge/MainChallengeDetails.jsx
  src/views/saving/SavingCount.jsx
  src/views/saving/SavingRate.jsx
  src/views/saving/SavingTotalAmount.jsx
  yarn.lock
Labels: feature develop

#19 [김보미] implement show challenge d-day & filtering pop-up & text change
  public/modules/challenge_account.json
  public/modules/saving.json
  src/images/history_filter.png
  src/index.html
  src/pages/saving/Saving.jsx
  src/redux/actions/types.js
  src/redux/reducers/savingHistoryReducer.js
  src/views/challenge/MainChallengeDetails.jsx
  src/views/saving/SavingFilterPopUp.jsx
  src/views/saving/SavingHistoryItem.jsx
  src/views/saving/SavingHistoryList.jsx
  src/views/saving/SavingRate.jsx
  src/views/saving/SavingStartButton.jsx
  src/views/saving/SavingTotalAmount.jsx
Labels: complete, ui develop, feature develop

#22 [김보미] Add axios logic for history filter & challenge info data to deposit view
  public/modules/autoSaving.json
  public/modules/challenge_account.json
  public/modules/history_acient.json
  src/pages/saving/Saving.jsx
  src/redux/reducers/savingInfoReducer.js
  src/views/deposit/DepositView.jsx
  src/views/saving/AutoSavingButton.jsx
  src/views/saving/SavingAccount.jsx
  src/views/saving/SavingFilterPopUp.jsx
  src/views/saving/SavingHistoryItem.jsx
  src/views/saving/SavingHistoryList.jsx
  src/views/saving/SavingStartButton.jsx
Labels: ui develop, feature develop

#26 [이동수] Completion of Challenge Payment page and Challenge Payment Success page
  public/modules/challenge.json
  src/App.jsx
  src/components/Event.jsx
  src/components/Thimbnail.jsx
  src/images/Character.png
  src/pages/challenge/Challenge.jsx
  src/pages/challenge/ChallengeContainer.jsx
  src/pages/challenge/ChallengePayment.jsx
  src/pages/challenge/ChallengePaymentSuccess.jsx
  src/pages/main/Main.jsx
  src/views/challenge/PayBtn.jsx
  src/views/challenge/SavingDay.jsx
Labels: documentation, complete, ui develop, feature develop

#28 [김보미] Saving room & Saving start page
  public/modules/challenge.json
  public/modules/saving.json
  src/components/Button.jsx
  src/pages/challenge/ChallengeContainer.jsx
  src/pages/saving/Saving.jsx
  src/pages/saving/SavingDeposit.jsx
  src/pages/saving/SavingHistoryContainer.jsx
  src/pages/saving/SavingRoomInfoContainer.jsx
  src/pages/saving/SavingStatusContainer.jsx
  src/views/deposit/DepositView.jsx
  src/views/saving/SavingHistory.jsx
  src/views/saving/SavingMenuButton.jsx
  src/views/saving/SavingRate.jsx
  src/views/saving/SavingRoomInfo.jsx
  src/views/saving/SavingStartButton.jsx
  src/views/saving/SavingStatusInfo.jsx
  src/views/saving/SavingTabMenu.jsx
Labels: complete, ui develop, feature develop

#31 [김보미] Refactoring Some logic & Implement saving keypad
  public/modules/challenge.json
  public/modules/saving.json
  src/App.jsx
  src/components/Button.jsx
  src/components/Portal.jsx
  src/images/popup_close.png
  src/images/remove_arrow.png
  src/images/saving_finish.png
  src/pages/challenge/ChallengePaymentSuccess.jsx
  src/views/deposit/DepositKeypad.jsx
  src/views/deposit/DepositView.jsx
  src/views/deposit/Keypad.jsx
  src/views/deposit/SavingSuccess.jsx
  src/views/saving/AutoSavingButton.jsx
  src/views/saving/SavingFinishPopUp.jsx
  src/views/saving/SavingHistory.jsx
  src/views/saving/SavingHistoryList.jsx
  src/views/saving/SavingRate.jsx
  src/views/saving/SavingRoomInfo.jsx
  src/views/saving/SavingStartButton.jsx
Labels: complete, ui develop, feature develop, refactoring

#32 [이동수] Feature : 더보기 button & navigate & component created
  public/modules/challenge.json
  public/modules/participatingChallenge.json
  public/modules/popularChallenge.json
  public/modules/wholeChallenge.json
  src/App.jsx
  src/components/ChallengeTemplate1.jsx
  src/components/ChallengeTemplate2.jsx
  src/components/LikeButton.jsx
  src/components/MoreShowBtn.jsx
  src/images/Circle.png
  src/pages/MoreShow/MoreShow.jsx
  src/pages/challenge/ChallengeContainer.jsx
  src/views/MoreShow/MoreShowTemplate.jsx
  src/views/main/ChallengeCreateAndEct.jsx
  src/views/main/MainTabs.jsx
Labels: enhancement, ui develop, feature develop
